apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alert-rules
  namespace: logging
  labels:
    loki_rule: "1"
data:
  loki-rules.yaml: |
    groups:
      - name: loki-log-alerts
        rules:
          - alert: HighErrorRateInLogs
            expr: |
              sum(rate({namespace=~".+"} |= "error" [5m])) > 2
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High error rate in logs"
              description: "More than 2 log lines/min containing 'error' during 2 minutes."

          - alert: PanicOrFatalInLogs
            expr: |
              sum(rate({namespace=~".+"} |~ "(?i)(panic|fatal)" [5m])) > 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Panic/Fatal in logs"
              description: "Found 'panic' or 'fatal' in logs."
